services:
  web:
    container_name: 'quest-board_web'
    build:
      context: ./docker/web
    ports:
      - 8000:80
    depends_on:
      - app
    volumes:
      - ./src:/app

  app:
    container_name: 'quest-board_app'
    build:
      context: ./docker/app
    volumes:
      - ./src:/app
    depends_on:
      - db

  db:
    container_name: 'quest-board_db'
    build:
      context: ./docker/db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: quest-board
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - quest-board_volume:/var/lib/mysql

volumes:
  quest-board_volume:
